### PR TITLE
Feature: Add MountPoint checks.

### PR DESCRIPTION
**Pull request by Poogles**
Spotted these weren't added.  Implements [MountPoint](https://testinfra.readthedocs.io/en/latest/modules.html#mountpoint) from testinfra.

Tried to keep the names/style in keeping and added an example.

Tested as working, although IMO it's starting to get a little hairy without any automated tests for some of the checks.

### CODE REVIEW

**Comment by ssplatt** [comment]
yep. tests are definitely needed. at some point i'll get some free time and write some.

**Comment by Poogles** [comment]
@ssplatt I've probably got another few PR's on the way.  With this in mind I'll add some tests for this and what comes in future; I'm assuming you'll be using pytest?

**Comment by ssplatt** [comment]
i've got the travis config ready for nosetests, but we can add in something else if needed.
https://github.com/ssplatt/saltstack-infratest-module/blob/master/.travis.yml#L16

I really haven't put much thought into what's best yet.

**Comment by Poogles** [comment]
I'll run through everything with pytest (it's simpler than nose/unittest if you haven't used it) in the next week or so and open another PR.

**Pull request merged**
